version: "3"
services:
  app:
    build: .
    image: users-app
    container_name: users-app
    ports:
      - 9001:9001
    networks:
      - dogsonskateboards
    volumes:
      - .:/app
    command: ["npm", "start"]
networks:
  dogsonskateboards:
